import React from "react";
import Square from "../Square";

export default function Board(squareProp, setTurn, turn, setSquares) {
  return (
    <div className="squares">
      <table>
        <tbody>
          <tr>
            <Square
              square={squareProp}
              setTurn={setTurn}
              turn={turn}
              setSquares={setSquares}
              num={0}
            />
            <Square
              square={squareProp}
              setTurn={setTurn}
              turn={turn}
              setSquares={setSquares}
              num={1}
            />
            <Square
              square={squareProp}
              setTurn={setTurn}
              turn={turn}
              setSquares={setSquares}
              num={2}
            />
          </tr>
          <tr>
            <Square
              square={squareProp}
              setTurn={setTurn}
              turn={turn}
              setSquares={setSquares}
              num={3}
            />
            <Square
              square={squareProp}
              setTurn={setTurn}
              turn={turn}
              setSquares={setSquares}
              num={4}
            />
            <Square
              square={squareProp}
              setTurn={setTurn}
              turn={turn}
              setSquares={setSquares}
              num={5}
            />
          </tr>
          <tr>
            <Square
              square={squareProp}
              setTurn={setTurn}
              turn={turn}
              setSquares={setSquares}
              num={6}
            />
            <Square
              square={squareProp}
              setTurn={setTurn}
              turn={turn}
              setSquares={setSquares}
              num={7}
            />
            <Square
              square={squareProp}
              setTurn={setTurn}
              turn={turn}
              setSquares={setSquares}
              num={8}
            />
          </tr>
        </tbody>
      </table>
    </div>
  );
}
